version: '3.1'

services:
  frontBack:
    image: frontback
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=koe
      - DB_PASSWORD=ps8koeps8
      - DB_HOST=db_mongo
      - DB_PORT=27017
    depends_on:
      - db_mongo

  db_mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: koe
      MONGO_INITDB_ROOT_PASSWORD: ps8koeps8
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: